sonar.projectKey=hoanhophuoc_IT-Tools
sonar.organization=hoanhophuoc

# Display name and version in SonarQube Cloud
sonar.projectName=IT-Tools
sonar.projectVersion=1.0

# Source directories relative to root
sonar.sources=backend,frontend/src

# Exclude generated code and external dependencies
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/.next/**,**/*.spec.js,**/*.test.js

# Encoding of the source code
sonar.sourceEncoding=UTF-8
